### PR TITLE
118 restructure object directory

### LINKED ISSUE #73: Integration testing for existing functionality

### LINKED ISSUE #118: Restructure object directory
Adding folders to structuralize the object folder
look at how sharp-wrapper do it

### PR DESCRIPTION
**Pull request by whatdoes3plus1equalsto**
closes #118 
closes #73

### CODE REVIEW

**Comment by whatdoes3plus1equalsto** [comment]
removed validator unit test since its no longer possible to test it offline

**Review by VanJackal — COMMENTED** [review]
this is currently breaking react, not sure whats wrong ill look into it

**Comment by whatdoes3plus1equalsto** [comment]
Need to rewrite the import for each files for testing

**Review by VanJackal — APPROVED** [review]
seems to be working now

**Pull request merged**
